CC = gcc
CFLAGS = -I../common -g -DWIN32 -DNEED_BSDCOMPAT
OBJS = ctfserv.o ctfsocket.o object.o control.o map.o strlcpy.o
LIBS = -lwsock32
CTFSERVER = ctfserver.exe

all:	ctfserver

ctfserver:	$(OBJS)
	$(CC) -o $(CTFSERVER) $(CFLAGS) $(OBJS) $(LIBS)

clean:
	rm -f $(OBJS) $(CTFSERVER)

