CC=gcc
CFLAGS=-Wall -DDEBUG -DWIN32 -DNEED_ERRTABLE -DNEED_BSDCOMPAT
OBJS=main.o datagram.o log.o session.o endian.o directory.o errortable.o tnfs_file.o strlcpy.o strlcat.o
LIBS=-lwsock32
EXEC=tnfsd.exe

all:	$(OBJS)
	$(CC) -o $(EXEC) $(OBJS) $(LIBS)

clean:
	$(RM) -f $(OBJS) $(EXEC)

