DEFC PAGEIN = 0x3FF9
DEFC PAGEOUT = 0x007C
DEFC HLCALL = 0x3FFA
DEFC IXCALL = 0x3FFD
DEFC SOCKET = 0x3E00	; Allocate a socket
DEFC CLOSE = 0x3E03	; Close a socket
DEFC LISTEN = 0x3E06	; Listen for incoming connections
DEFC ACCEPT = 0x3E09	; Accept an incoming connection
DEFC BIND = 0x3E0C	; Bind a local address to a socket
DEFC CONNECT = 0x3E0F	; Connect to a remote host
DEFC SEND = 0x3E12	; Send data 
DEFC RECV = 0x3E15	; Receive data 
DEFC SENDTO = 0x3E18	; Send data to an address
DEFC RECVFROM = 0x3E1B	; Receive data from an address
DEFC POLL_ROM = 0x3E1E	; Poll a list of sockets
DEFC POLLALL_ROM = 0x3E21	; Poll all open sockets
DEFC POLLFD_ROM = 0x3E24	; Poll a single socket
DEFC GETHOSTBYNAME_ROM = 0x3E27	; Look up a hostname
DEFC PUTCHAR42 = 0x3E2A	; 42 column print write a character
DEFC PRINT42 = 0x3E2D	; 42 column print a null terminated string
DEFC CLEAR42 = 0x3E30	; Clear the screen and reset 42-col print
DEFC SETPAGEA = 0x3E33	; Sets page area A
DEFC SETPAGEB = 0x3E36	; Sets page area B
DEFC LONG2IPSTRING = 0x3E39	; Convert a 4 byte big endian long to an IP
DEFC IPSTRING2LONG = 0x3E3C	; Convert an IP to a 4 byte big endian long
DEFC ITOA8 = 0x3E3F	; Convert a byte to ascii
DEFC RAND16 = 0x3E42	; 16 bit PRNG
DEFC REMOTEADDRESS = 0x3E45	; Fill struct sockaddr_in
DEFC POLLNVAL = 0x80
DEFC REGDUMP = 0x3E48

